name: Content Management Interface
version: '${project.version}'
main: org.waffledevelopment.cmi.CMI
api-version: 1.19
authors: [ WaffleDevelopment ]
description: a Custom CMI spigot Plugin Made by Waffle Lovers
commands:
  afk:
    description: Toggle afk mode.
  afkCheck:
    description: Checks IF Player is AFK.
  air:
    description: Sets a Players Air Level.

permissions:
  WMI.admin:
    description: Administrator permission.
  WMI.command.ban:
    description: Permission to use ban Command
  WMI.command.ban.bypass:
    description: Permission to bypass Ban
  WMI.command.sudo:
    description: Permission to use sudo Command.
  WMI.command.afkcheck:
    description: Permission to use afkcheck command.